Adhere to async and reactive APIs
dwdougherty/redis-doc pull request #1
Opened 2024-03-21 11:18 UTC by uglide

2024-03-21 13:09 UTC, sazzad16 requested changes

2024-03-21 13:09 UTC, sazzad16 commented on docs/connect/clients/lettuce.md
> +Lettuce comes with an asynchronous, non-blocking pool implementation to be used with Lettuces asynchronous connection methods. It does not require additional dependencies.
> Lettuce comes with an asynchronous, non-blocking pool implementation ...

NO, IT DOESN'T.
The pool implementation is actually of commons-pool2 library.
Lettuce provides _wrapper_ classes (e.g. `BoundedPoolConfig`) for commons-pool2 config classes.

> It does not require additional dependencies.

IT DOES. E.g. `BoundedPoolConfig.create()` below depends on commons-pool2 library. The statement will fail without that library.

```suggestion
Lettuce provides pool config to be used with Lettuces asynchronous connection methods.
```

2024-03-21 13:09 UTC, sazzad16 commented on docs/connect/clients/lettuce.md
> +These connections are multiplexed; that is, multiple commands can be run concurrently over a single or a small set of connections, making explicit pooling less critical than in blocking clients like
Also, it is not _less critical_ anymore when you introduce pooling.

2024-03-21 13:09 UTC, sazzad16 commented on docs/connect/clients/lettuce.md
> +        BoundedPoolConfig.create());
It is worth considering a detailed config; e.g. `BoundedPoolConfig.builder().maxTotal(100).maxIdle(20).minIdle(5).build()`.

2024-03-21 13:18 UTC, dwdougherty commented on docs/connect/clients/lettuce.md
> +        BoundedPoolConfig.create());
@sazzad16 I'm not a Java programmer, as you could likely tell. Would I just replace the line:

BoundedPoolConfig.create());

with the line you provided in your comment?

2024-03-21 13:30 UTC, dwdougherty commented on docs/connect/clients/lettuce.md
> +        BoundedPoolConfig.create());
Also, thank you very much for the other comments! Much appreciated.

2024-03-21 14:27 UTC, tishun commented on docs/connect/clients/lettuce.md
> +      // Asynchronously store key-value pairs in a hash directly
What is the benefit of this specific example?
Perhaps we can show here some other feature that makes sense in an async approach, e.g. handling errors?

2024-03-21 14:27 UTC, tishun commented on docs/connect/clients/lettuce.md
> +      reactiveCommands.set("foo", "bar").block();
To fully take advantage of the async approach we should try and block once for this, similar to the example I added for the Async/Future approach

2024-03-21 14:27 UTC, tishun commented on docs/connect/clients/lettuce.md
> +      reactiveCommands.hset("user-session:124", hash).then(
I think we should handle all the error cases, just to show the best practices.

Applies to all examples.

2024-03-21 14:35 UTC, tishun commented on docs/connect/clients/lettuce.md
> +        BoundedPoolConfig.create());
Can't we just use the example in https://github.com/lettuce-io/lettuce-core/wiki/Connection-Pooling ?

2024-03-21 14:57 UTC, dwdougherty commented on docs/connect/clients/lettuce.md
> +      // Asynchronously store key-value pairs in a hash directly
The other client guides all use mostly the same examples, so that's why this is here.

2024-03-21 15:51 UTC, sazzad16 commented on docs/connect/clients/lettuce.md
> +        BoundedPoolConfig.create());
@dwdougherty Yes, you can simply replace `BoundedPoolConfig.create()` with line/statement in my comment.

2024-03-22 13:26 UTC, dwdougherty commented on docs/connect/clients/lettuce.md
> +      // Asynchronously store & retrieve a simple string
Thank you @tishun. I'll make a note of this for the next iteration.

2024-03-22 15:07 UTC, dwdougherty approved these changes

2024-03-22 15:08 UTC, merged